/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@zebra/core/dist/**/*.{js,ts,jsx,tsx,cjs,mjs,js,ts}",
  ],
  safelist: [
    "bg-background",
    "bg-background/80",
    "bg-card",
    "text-card-foreground",
    "backdrop-blur-sm",
    "border",
    "shadow-lg",
    "rounded-xl",
    // ToggleSwitch
    "h-6",
    "w-11",
    "h-5",
    "w-5",
    "h-4",
    "w-4",
    "w-9",
    "translate-x-[20px]",
    "translate-x-[16px]",
    "translate-x-0.5",
    "bg-primary",
    "bg-gray-200",
    "dark:bg-gray-700",
    "rounded-full",
    "shadow-sm",
    "transition-transform",
    "transition-colors",
    "focus:ring-2",
    "focus:ring-offset-2",
    "focus:outline-none",
    "absolute",
    "top-0.5",
    // Select
    "relative",
    "flex",
    "h-10",
    "w-full",
    "appearance-none",
    "rounded-md",
    "border",
    "border-gray-300",
    "bg-transparent",
    "px-3",
    "py-2",
    "text-sm",
    "disabled:cursor-not-allowed",
    "disabled:opacity-50",
    "dark:border-gray-700",
    "dark:bg-gray-900",
    "dark:text-gray-100",
    "pointer-events-none",
    "top-3",
    "right-3",
    "text-gray-500",
    "opacity-50",
    "dark:text-gray-400",
  ],
  theme: {
    extend: {
      colors: {
        "board-bg": "var(--wood-bg)",
        "board-line": "var(--board-line)",
        primary: "var(--primary)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        sans: ["var(--font-family)"],
      },
    },
  },
  plugins: [],
};
